### ISSUE TITLE
Upgrade of Tesla node server failed

### ISSUE THREAD

**Issue by pgattu** [UniversalDevicesInc/tesla-nodeserver#11]
I tried to update the Tesla node server from the Node Server Store.  I see the below error in debug.log file.  How do I update the node server?  The "Update" button is not available in the Node Server Store anymore.

[12/30/2019, 2:44:13 PM - error: NSChild: Tesla pullRepo: Error: runInstallProcess: undefined
12/30/2019, 2:44:13 PM - error: Error: runInstallProcess: undefined
    at runInstallProcess (/snapshot/polyglot-v2/lib/modules/children.js:45:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
12/30/2019, 2:44:13 PM - error: NSResponse: Success: false - pullRepo: runInstallProcess: undefined
](url)

**Comment by pgattu** [comment]
I am closing this issue since I reinstalled my OS and reinstalled Polyglot-v2.
