### ISSUE TITLE
ver 2.3.0 error code 408 - use WAKE cmd to wake it up 2020-03-18 04:29:55 error: NS: Vehicle add failed: TypeError: Cannot read property 'gui_distance_units' of undefined at Vehicle.vehicleUOM 

### ISSUE THREAD

**Issue by psmith3** [UniversalDevicesInc/tesla-nodeserver#17]
I am not sure what to make of this error. Installed for the 1st time tonight for this Tesla account. Any idea?

`2020-03-18 04:29:54 info: NS: Tesla sleeping and returned error code 408 - use WAKE cmd to wake it up
2020-03-18 04:29:54 error: NS: Vehicle add failed: TypeError: Cannot read property 'gui_distance_units' of undefined
    at Vehicle.vehicleUOM (/root/.polyglot/nodeservers/Tesla/Nodes/Vehicle.js:194:22)
    at Vehicle.initializeUOM (/root/.polyglot/nodeservers/Tesla/Nodes/Vehicle.js:84:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-03-18 04:29:55 info: NS: Tesla sleeping and returned error code 408 - use WAKE cmd to wake it up
2020-03-18 04:29:55 error: NS: Vehicle add failed: TypeError: Cannot read property 'gui_distance_units' of undefined
    at Vehicle.vehicleUOM (/root/.polyglot/nodeservers/Tesla/Nodes/Vehicle.js:194:22)
    at Vehicle.initializeUOM (/root/.polyglot/nodeservers/Tesla/Nodes/Vehicle.js:84:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-03-18 04:29:55 info: NS: Tesla Vehicles: 2, added to Polyglot: 0`

**Comment by psmith3** [comment]
After waking car and removing and reinstalling node server, it started working.
