### ISSUE TITLE
"Node oller not found"

### ISSUE THREAD

**Issue by oddboy** [UniversalDevicesInc/tesla-nodeserver#18]
Hi there,

love this node server, it's awesome!

I was watch the log on mine recently (which runs on PGC) and observed this error:

"error: PGC: Node oller not found"

the node seems to work ok, but I thought I'd document it for you.

Also, from the looks of the log, the node server always polls at the short interval.  It never polls on the long interval.

below is a little more context from the log.  vehicle id obfuscated.

----
```
2020-06-07 08:31:38 info: NS: Config received has 6 nodes
2020-06-07 08:31:52 info: NS: Tesla API: /api/1/vehicles/1234567890/vehicle_data
2020-06-07 08:31:52 info: NS: Short poll
2020-06-07 08:31:52 info: NS: Reusing existing tokens
    at VehicleWakeMode.updateOtherNodes (/app/nodeserver/Nodes/VehicleWakeMode.js:166:22)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
2020-06-07 08:31:53 error: NS: Error while querying vehicle: TypeError: Cannot read property 'updateOtherNodes' of undefined
    at VehicleWakeMode.queryVehicle (/app/nodeserver/Nodes/VehicleWakeMode.js:240:14)
    at VehicleWakeMode.processDrivers (/app/nodeserver/Nodes/VehicleWakeMode.js:256:14)
2020-06-07 08:31:53 error: PGC: Node oller not found
2020-06-07 08:31:53 info: NS: Config received has 6 nodes
2020-06-07 08:32:07 info: NS: Short poll
2020-06-07 08:32:07 info: NS: Tesla API: /api/1/vehicles/1234567890/vehicle_data
2020-06-07 08:32:07 info: NS: Reusing existing tokens
2020-06-07 08:32:08 error: NS: Error while querying vehicle: TypeError: Cannot read property 'updateOtherNodes' of undefined
    at VehicleWakeMode.updateOtherNodes (/app/nodeserver/Nodes/VehicleWakeMode.js:166:22)
2020-06-07 08:32:08 error: PGC: Node oller not found
    at VehicleWakeMode.processDrivers (/app/nodeserver/Nodes/VehicleWakeMode.js:256:14)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
    at VehicleWakeMode.queryVehicle (/app/nodeserver/Nodes/VehicleWakeMode.js:240:14)
2020-06-07 08:32:08 info: NS: Config received has 6 nodes
2020-06-07 08:32:22 info: NS: Short poll
2020-06-07 08:32:22 info: NS: Tesla API: /api/1/vehicles/1234567890/vehicle_data
2020-06-07 08:32:22 info: NS: Reusing existing tokens
2020-06-07 08:32:23 error: NS: Error while querying vehicle: TypeError: Cannot read property 'updateOtherNodes' of undefined
2020-06-07 08:32:23 error: PGC: Node oller not found
    at VehicleWakeMode.updateOtherNodes (/app/nodeserver/Nodes/VehicleWakeMode.js:166:22)
    at VehicleWakeMode.processDrivers (/app/nodeserver/Nodes/VehicleWakeMode.js:256:14)
    at VehicleWakeMode.queryVehicle (/app/nodeserver/Nodes/VehicleWakeMode.js:240:14)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
2020-06-07 08:32:23 info: NS: Config received has 6 nodes

    
```

**Comment by oddboy** [comment]
still can't get this pgc server to work reliably.  the "wake mode" seems to revert to off if I leave the "Wake Mode" node.

If there's anything I can do to help, I'm happy to do so....

**Comment by blakevh** [comment]
Wake mode does time out after the long poll time.  This is on purpose since Wake mode causes the car to stay awake and does not allow it to go into sleep mode.  When the car is awake it is using more power.

If you restart the nodeserver, have you noticed if the "error: PGC: Node oller not found" happens right away, or does it happen after a specific interval, or after a specific type of event?
