### ISSUE TITLE
deprecated dependencies?

### ISSUE THREAD

**Issue by oddboy** [UniversalDevicesInc/tesla-nodeserver#19]
Hi there,

I recently noticed that my polyglot tesla node wasn't retrieving status from my car.  when I restarted it, I noticed that several include libs are marked "deprecated".

`Cloning into 'nodeserver'...
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN tesla@2.3.0 No repository field.

added 258 packages from 212 contributors and audited 258 packages in 14.006s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
2020-09-14 06:46:16 info: NS: -------------------------------------------------------
2020-09-14 06:46:16 info: NS: Starting Tesla Node Server
2020-09-14 06:46:16 info: PGC: Polyglot topic: prod/ns/tesla-0021b9024451-3
2020-09-14 06:46:16 info: PGC: Logging topic: prod/frontend/5b64751a30ace875f5456869/logs/tesla-0021b9024451-3
2020-09-14 06:46:16 info: PGC: Interface starting
2020-09-14 06:46:16 info: PGC: MQTT client connected
2020-09-14 06:46:16 info: NS: MQTT Connection started
2020-09-14 06:46:16 info: PGC: Set shortPoll value to 60
2020-09-14 06:46:16 info: PGC: Set longPoll value to 900
2020-09-14 06:46:16 info: NS: Config received has 1 nodes
2020-09-14 06:46:16 info: NS: Running nodeserver in the cloud
2020-09-14 06:46:16 info: NS: Config received has 1 nodes
2020-09-14 06:46:17 info: NS: Config received has 1 nodes
2020-09-14 06:47:17 info: NS: Short poll`

Is this a problem?

the newly launched instance of this node server appears to not work.  I never get more than 1 node, and my username/password is absolutely correct.

thanks,

Joel

**Comment by blakevh** [comment]
I have noticed the deprecated package issue.  The deprecated libraries probably are not the cause of an issue.  I am working on an update for the deprecated libraries anyway.

1. is your car awake prior to saving your credentials?  Sometimes the car can take too long to wake up causing the additional nodes to fail to create.
2. are there any other additional log messages, probably around the Long poll that are failing?

**Comment by oddboy** [comment]
Hi there,

I don't actually see any long polls, just short ones.

here's something:


2020-09-15 02:43:33 error: NS: Error discovering vehicles: RequestError: Error: connect ETIMEDOUT 205.234.31.120:443

    at new RequestError (/app/nodeserver/node_modules/request-promise-core/lib/errors.js:14:15)

    at Request.RP$callback [as _callback] (/app/nodeserver/node_modules/request-promise-core/lib/plumbing.js:46:31)

2020-09-15 02:43:33 error: NS: Tesla API /api/1/vehicles returned: Error: connect ETIMEDOUT 205.234.31.120:443

    at Request.plumbing.callback (/app/nodeserver/node_modules/request-promise-core/lib/plumbing.js:87:29)

    at Request.onRequestError (/app/nodeserver/node_modules/request/request.js:877:8)

    at Request.emit (events.js:193:13)

    at ClientRequest.emit (events.js:193:13)

    at TLSSocket.socketErrorListener (_http_client.js:397:9)

    at self.callback (/app/nodeserver/node_modules/request/request.js:185:22)

    at emitErrorNT (internal/streams/destroy.js:91:8)

    at TLSSocket.emit (events.js:193:13)

2020-09-15 02:43:41 info: NS: Short poll


________________________________

**Comment by oddboy** [comment]
actually, here's the complete log for a new node server.  My car is awake while I did this.



________________________________

**Comment by blakevh** [comment]
Interesting.  The error

`2020-09-15 02:43:33 error: NS: Tesla API /api/1/vehicles returned: Error: connect ETIMEDOUT 205.234.31.120:443`

is a failure to connect to the Tesla API endpoint.  My test environment is connecting fine.  I wonder if we are hitting a rate limit from the production installation.  I will try later from the production installation.

**Comment by oddboy** [comment]
SO it actually looks like maybe the certificate is invalid.

here's the error from the tesla node log:

----
2020-09-19 02:23:56 info: NS: Short poll 2020-09-19 02:23:56 error: NS: Tesla API /api/1/vehicles returned: Error: connect ETIMEDOUT 205.234.31.120:443 2020-09-19 02:23:56 error: NS: Error discovering vehicles: RequestError: Error: connect ETIMEDOUT 205.234.31.120:443     at new RequestError (/app/nodeserver/node_modules/request-promise-core/lib/errors.js:14:15)     at Request.plumbing.callback (/app/nodeserver/node_modules/request-promise-core/lib/plumbing.js:87:29)     at Request.RP$callback [as _callback] (/app/nodeserver/node_modules/request-promise-core/lib/plumbing.js:46:31)     at self.callback (/app/nodeserver/node_modules/request/request.js:185:22)     at Request.emit (events.js:193:13)     at Request.onRequestError (/app/nodeserver/node_modules/request/request.js:877:8)     at ClientRequest.emit (events.js:193:13)     at TLSSocket.socketErrorListener (_http_client.js:397:9)     at TLSSocket.emit (events.js:193:13)     at emitErrorNT (internal/streams/destroy.js:91:8) 2020-09-19 02:23:57 info: NS: Config received has 1 nodes 2020-09-19 02:24:11 info: NS: Short poll
----

when I visit that IP address directly on HTTPS, I go into a loop with a certificate error.  it does indeed look like a TESLA problem...
https://search.arin.net/rdap/?query=205.234.31.120
[https://www.current.qa.arin.net/img/logo-social.png]<https://search.arin.net/rdap/?query=205.234.31.120>
ARIN Whois/RDAP<https://search.arin.net/rdap/?query=205.234.31.120>
ARIN is a nonprofit, member-based organization that administers IP addresses & ASNs in support of the operation and growth of the Internet.
search.arin.net

Looks like the certificate is issued to: Kubernetes Ingress Controller Fake Certificate.

Does your code expect valid certs, or will it trust self signed ones?

thanks,

Joel
________________________________

**Comment by oddboy** [comment]
actually, if I use the hostname "https://owner-api.teslamotors.com/", then the TLS connection works, but by IP address, it doesn't.

do you use the hostname or the IP directly?

thanks,

Joel

________________________________

**Comment by blakevh** [comment]
The Tesla nodeserver does access the API through https://owner-api.teslamotors.com  .  The Tesla Ingress controller probably only maps the name.

**Comment by blakevh** [comment]
The existing release code 2.3.0 works on my development Raspberry Pi Polyglot installation, it also works on my Polisy.
But I also see a similar "error: NS: Tesla API /api/1/vehicles returned: Error: connect ETIMEDOUT " when I configure the nodeserver on the cloud hosted https://polyglot.isy.io/  .

**Comment by oddboy** [comment]
DO you think there's anything I can do?

-----

2020-09-22 02:30:47 info: NS: Short poll

2020-09-22 02:30:53 error: NS: Tesla API /api/1/vehicles returned: Error: connect ETIMEDOUT 205.234.31.120:443

    at Request.emit (events.js:193:13)

    at Request.RP$callback [as _callback] (/app/nodeserver/node_modules/request-promise-core/lib/plumbing.js:46:31)

    at TLSSocket.socketErrorListener (_http_client.js:397:9)

    at Request.plumbing.callback (/app/nodeserver/node_modules/request-promise-core/lib/plumbing.js:87:29)

    at new RequestError (/app/nodeserver/node_modules/request-promise-core/lib/errors.js:14:15)

    at Request.onRequestError (/app/nodeserver/node_modules/request/request.js:877:8)

    at self.callback (/app/nodeserver/node_modules/request/request.js:185:22)

2020-09-22 02:30:53 error: NS: Error discovering vehicles: RequestError: Error: connect ETIMEDOUT 205.234.31.120:443

    at ClientRequest.emit (events.js:193:13)

2020-09-22 02:30:53 info: NS: Config received has 1 nodes

    at emitErrorNT (internal/streams/destroy.js:91:8)

    at TLSSocket.emit (events.js:193:13)

2020-09-22 02:30:53 info: NS: Config received has 1 nodes

2020-09-22 02:30:53 info: NS: Config received has 1

________________________________

**Comment by oddboy** [comment]
I'm not 100% sure, but do you need to add the "Host: " header to teslaApiHost contant maybe?

I'm grasping a bit, i'm sure.  This node server worked perfectly for months, and now, not at all... 🙁

J

________________________________

**Comment by oddboy** [comment]
I guess only option is to try a local install?
