### ISSUE TITLE
Nodes do not populate in isy

### ISSUE THREAD

**Issue by Cglass-1234** [UniversalDevicesInc/tesla-nodeserver#23]
Recently I noticed that the data in the Tesla nodes in my ISY was not correct, or missing altogther.

Regardless of how I queried the node, or updated the node, the data did not change.

I deleted the node from the PGC.  Reinstalled.  Several times.  I am now noticing the following:

2021-02-13 16:43:19 info: NS: Discovering new vehicles
2021-02-13 16:43:19 info: NS: Tesla API: /api/1/vehicles
2021-02-13 16:43:19 info: NS: Getting new tokens
2021-02-13 16:43:19 error: NS: Tesla API /api/1/vehicles returned: 400 - {"response":null,"error":"Endpoint deprecated: Please update your App.","error_description":""}
2021-02-13 16:43:19 error: NS: Error discovering vehicles: StatusCodeError: 400 - {"response":null,"error":"Endpoint deprecated: Please update your App.","error_description":""}
    at new StatusCodeError (/app/nodeserver/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/app/nodeserver/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/app/nodeserver/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/app/nodeserver/node_modules/request/request.js:185:22)
    at Request.emit (events.js:193:13)
    at Request.<anonymous> (/app/nodeserver/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:193:13)
    at IncomingMessage.<anonymous> (/app/nodeserver/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:281:20)
    at IncomingMessage.emit (events.js:198:15)

Please advise.

Regards

Carl

**Comment by blakevh** [comment]
Hi, Carl,

Tesla recently implemented a new authentication method for their API.  We are aware of the issue, but do not yet have an implementation that supports the new authentication method.

Thanks

**Comment by Cglass-1234** [comment]
Yes, I'm aware.  I also use TeslaFi.com and recently had to generate a new API token for proper authentication.  Is it as simple as adding an API field to your nodeserver?

**Comment by blakevh** [comment]
The authentication method is radically different from the previous version.  The new method supports both multi-factor authentication and non-multi-factor authentication and has a different workflow.  From the user perspective, if we continue to support username/password entry, we will also have to add a multi-factor device name and a transient multi-factor code.  Rather than re-implementing the authentication from scratch I am looking for a compatible authentication library.  So far I have only found one library that is compatible with our environment and works.  Even that library I had to fix to get to work in a simple test-bed.  And with a working library, there is still work that needs to be done to hook it into the Tesla nodeserver.

**Comment by Cglass-1234** [comment]
Robert

 

I see that you have released 3.0.0 and 3.0.1 of the Tesla Nodeserver.  I installed, and the nodeserver promptly appeared.  But my vehicle hasn’t appeared yet.  I’m only using email and password in the nodeserver config page.  I also input a lat long and true security.  Only one node named “controller” is shown in pgc.

 

Must I use mfa, and if so, how do I configure that.  I can’t find any instructions.

 

Thx!

 

Carl

**Comment by blakevh** [comment]
@Cglass-1234 so far I have only succeeded in getting the Tesla nodeserver to work on a Polisy device with the new authentication protocols.  Like you described, the Tesla nodeserver fails to load on the Polyglot cloud.

Both regular and MFA logins should work on a Polisy device.

If you want to use an MFA login, you need to set up MFA on your Tesla account.  Go to https://www.tesla.com/support/multi-factor-authentication and follow the instructions.  If you set up only one MFA device, when you configure the nodeserver you just need to enter the MFA code.  If you setup up two MFA devices, you need to enter the MFA device name as well.

**Comment by Cglass-1234** [comment]
Ok, thx for the reply.  I’ll delete the nodeserver for now and wait for explicit confirmation that it works on pgc.

 

Thx

 

Carl
